name: wewire_maintenance_system
description: "Maintenance communication system for operators, quality agents, and maintenance service"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_core_web: ^3.0.0
  js: ^0.6.7
  uuid: ^4.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  file_picker: ^10.3.2
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^19.4.1
  flutter_typeahead: ^5.0.1
  flutter_slidable: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
