name: wewire_maintenance_system
description: "Maintenance communication system for operators, quality agents, and maintenance service"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.1
  firebase_core_web: ^2.17.0
  js: ^0.6.7
  uuid: ^4.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^16.3.0
  flutter_typeahead: ^5.0.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
