// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfhan6LH7r5TYWHn-7aOGhnPD5HH5GaXY',
    appId: '1:505805164580:web:330e793dd2337730f548b1',
    messagingSenderId: '505805164580',
    projectId: 'wewire-18bc2',
    authDomain: 'wewire-18bc2.firebaseapp.com',
    databaseURL: 'https://wewire-18bc2-default-rtdb.firebaseio.com',
    storageBucket: 'wewire-18bc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkshOHnxMV7P39qS_cSCSSMoARdapraeQ',
    appId: '1:505805164580:android:973439ec88414cf1f548b1',
    messagingSenderId: '505805164580',
    projectId: 'wewire-18bc2',
    databaseURL: 'https://wewire-18bc2-default-rtdb.firebaseio.com',
    storageBucket: 'wewire-18bc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KsYwlPLYAJs7Q7t4snnrz0t-bIDSSl0',
    appId: '1:505805164580:ios:3b2d0ee9be304ddcf548b1',
    messagingSenderId: '505805164580',
    projectId: 'wewire-18bc2',
    databaseURL: 'https://wewire-18bc2-default-rtdb.firebaseio.com',
    storageBucket: 'wewire-18bc2.firebasestorage.app',
    iosBundleId: 'com.example.wewireMaintenanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3KsYwlPLYAJs7Q7t4snnrz0t-bIDSSl0',
    appId: '1:505805164580:ios:3b2d0ee9be304ddcf548b1',
    messagingSenderId: '505805164580',
    projectId: 'wewire-18bc2',
    databaseURL: 'https://wewire-18bc2-default-rtdb.firebaseio.com',
    storageBucket: 'wewire-18bc2.firebasestorage.app',
    iosBundleId: 'com.example.wewireMaintenanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfhan6LH7r5TYWHn-7aOGhnPD5HH5GaXY',
    appId: '1:505805164580:web:86812bb30bd60cb5f548b1',
    messagingSenderId: '505805164580',
    projectId: 'wewire-18bc2',
    authDomain: 'wewire-18bc2.firebaseapp.com',
    databaseURL: 'https://wewire-18bc2-default-rtdb.firebaseio.com',
    storageBucket: 'wewire-18bc2.firebasestorage.app',
  );

}